ALTER TABLE public.profiles
ADD COLUMN calorie_goal INTEGER DEFAULT 2200,
ADD COLUMN protein_goal INTEGER DEFAULT 150,
ADD COLUMN carb_goal INTEGER DEFAULT 250,
ADD COLUMN fat_goal INTEGER DEFAULT 70;